//
//  Icons.swift
//  Equilibrium
//
//  Created by Vlad on 30. 1. 2026..
//

import Foundation

enum Icons {
    static let about = "info.circle.fill"
    static let antiStress = "sparkles"
    static let arrowTriangleCirclepath = "arrow.triangle.2.circlepath"
    static let arrowCounterclockwise = "arrow.counterclockwise"
    static let arrowDown = "arrow.down.circle.fill"
    static let arrowDownToLine = "arrow.down.to.line"
    static let arrowUp = "arrow.up.circle.fill"
    static let arrowUpArrowDown = "arrow.up.arrow.down"
    static let arrowUpLeftAndArrowDownRight = "arrow.up.left.and.arrow.down.right"
    static let atom = "atom"
    static let basketballFill = "basketball.fill"
    static let breath = "wind"
    static let boltFill = "bolt.fill"
    static let calendar = "calendar"
    static let chartBarXaxisDescending = "chart.bar.xaxis.descending"
    static let checkmarkCircleFill = "checkmark.circle.fill"
    static let circleDotted = "circle.dotted"
    static let circleFill = "circle.fill"
    static let circleHexagongrid = "circle.hexagongrid"
    static let circleHexagongridFill = "circle.hexagongrid.fill"
    static let clock = "clock"
    static let clockFill = "clock.fill"
    static let dropFill = "drop.fill"
    static let fire = "flame.fill"
    static let flameFill = "flame.fill"
    static let heartFill = "heart.fill"
    static let images = "photo.on.rectangle.angled"
    static let handPointUpLeftFill = "hand.point.up.left.fill"
    static let infoCircle = "info.circle"
    static let leafFill = "leaf.fill"
    static let leafCircle = "leaf.circle.fill"
    static let leftArrow = "chevron.left"
    static let mandala = "circle.hexagongrid"
    static let number = "number"
    static let pause = "play.circle.fill"
    static let pauseCircle = "pause.circle"
    static let pauseCircleFill = "pause.circle.fill"
    static let photoOnRectangleAngled = "photo.on.rectangle.angled"
    static let play = "pause.circle.fill"
    static let rectangle = "rectangle.fill"
    static let repeatCircleFill = "repeat.circle.fill"
    static let rightArrow = "chevron.right"
    static let slider = "slider.horizontal.3"
    static let sliderHorizontal = "slider.horizontal.3"
    static let sparkles = "sparkles"
    static let squareGrid = "square.grid.3x3"
    static let squareAndArrowUp = "square.and.arrow.up"
    static let speedometer = "speedometer"
    static let star = "star"
    static let starFill = "star.fill"
    static let timer = "timer"
    static let waveformPathEcg = "waveform.path.ecg"
    static let xmarkCircleFill = "xmark.circle.fill"
    static let xmark = "xmark"
    static let waveform = "waveform"
    static let wind = "wind"
}
